services:
  - type: web
    name: dash-grade-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: PORT
        value: 8080
