services:
  - type: web
    name: student-grade-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.10